### ISSUE TITLE
Virtual plane height

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/multi-contact-zmp#1]
Dear Dr. Caron,

In section V.B of the [paper](https://arxiv.org/pdf/1510.03232.pdf), you stated that the height of the virtual plane can be increased to grow the pendular support area. As far as I understood, by increasing the height of the virtual plane you try to reduce `omega_LNP` while the com height is constant. In this way the target of the ComTask in the z-direction is not changed, however by modifying `omega_LNP`, the LNPM model can be modified during the walking motion. Is it right?

**Comment by stephane-caron** [comment]
> by increasing the height of the virtual plane you try to reduce omega_LNP while the com height is constant.

That's right. The CoM height in the inertial frame stays the same. Moving the virtual plane only affects the dynamics of the linearized model, _i.e._ the natural frequency `omega`, _i.e._ the mapping from ZMP positions in the virtual plane to CoM accelerations in the inertial frame.
