### ISSUE TITLE
Stabilization problem in LNPM

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/multi-contact-zmp#2]
Hi Dr. Caron,

I'm writing to ask about the stabilization problem in linear non-inverted pendulum mode (LNPM) introduced in section IV of the [paper](https://arxiv.org/pdf/1510.03232.pdf). In your other [work](https://hal.archives-ouvertes.fr/hal-01875387/document), you have implemented a controller for the LIPM. This controller consists of two main components: DCM feedback control and whole-body admittance control. By DCM feedback control, you tried to control only the DCM of the LIPM rather than, e.g. both the CoM position and velocity. I would like to know which stabilizer can be implemented if we consider the LNPM.

**Comment by stephane-caron** [comment]
Sure, let's continue in the [lipm_walking_controller Discussions](https://github.com/stephane-caron/lipm_walking_controller/discussions/64).
